import type { Metadata } from "next";
import { GameProvider } from "@/context/GameContext";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import shuffleGame from "@/lib/shuffle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
  const initialGame = await shuffleGame();
  
  return (
    <html lang="en">
      <body
        
      >
        <GameProvider initialGame={initialGame}>{children}</GameProvider>
      </body>
    </html>
  );
}
